### PR TITLE
Sending data to ShowSlow

### PR DESCRIPTION
**Pull request by sergeychernyshev**
After I saw that you implemented jdrop support, I realized that DOM Monster data is the great addition to performance metrics tracked by ShowSlow so I added DOM Monster beacon to ShowSlow and a way to send data to it.

Right now results are only displayed in a breakdown section:
http://www.showslow.com/details/?url=http%3A%2F%2Fwww.google.com%2F#dommonster

I plan to add measurements history and graphing of these soon.

Had to rework some logic to separate gathering statistics from displaying them.

Users can modify data destination if they set up their own instance (instead of demo site) by setting SHOWSLOWINSTANCE variable to the root of their ShowSlow instance. If users drag bookmarklet from beacon page on their instance, it is already set for them - (example on demo site itself: http://www.showslow.com/beacon/dommonster/).

Would love to add more metrics in the future - especially some aggregated one ;)

Sergey

### CODE REVIEW

**Comment by madrobby** [comment]
Hi—this doesn't appear to work. I get a 400 Bad Request error.

**Comment by sergeychernyshev** [comment]
Strange, the link above seems to work fine. Can you post a HAR?

**Comment by madrobby** [comment]
I mean, it doesn't work when I add the patch, and click "send to showslow" in the DOM Monster.

Best,
Thomas

http://mir.aculo.us/

**Comment by sergeychernyshev** [comment]
Yeah, but 400 most likely means that it sent the beacon, but with wrong parameters or data.

I'll try to patch it again on my end and see what's wrong with it.

```
       Sergey
```

**Comment by sergeychernyshev** [comment]
Looks like patch was no longer applying to modified head - I've reapplied it and will submit updated pull request in a sec

**Pull request closed without merging**
