### PR TITLE
And another handful of changes...

### PR DESCRIPTION
**Pull request by FabianBeiner**
Hey,

that bookmarklet seriously woke up my interest in it self - so I've added a few more fixes/changes. Maybe review them and decide if they're worth to get pulled or not. :)

Gruß erm Greetings ;)
Fabian

### CODE REVIEW

**Comment by madrobby** [comment]
Thanks for the changes! Just try to keep the pull requests+commits very topical. Otherwise, it's too much work... :)

**Comment by FabianBeiner** [comment]
Okey, I'll try to commit not that much anymore, rather than when I'm actually really finished. ;)

**Comment by madrobby** [comment]
No worries! Would just like to have small, topical, concise additions! Especially if you can think of any other things that might be performance issues.

**Comment by FabianBeiner** [comment]
Are you going to pull the changes or should I change it to your style before? Or don't you want them at all? I'll see what could be useful in the coming days, when I actually work with web stuff again. ;)

**Pull request closed without merging**
